/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    // HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    // RouterLink: typeof import('vue-router')['RouterLink']
    // RouterView: typeof import('vue-router')['RouterView']
    Vheader: typeof import('./src/components/vheader.vue')['default']
  }
}

/**
 * declare module '@vue/runtime-core'
 *   现调整为
 * declare module 'vue'
 */
// import 'vue'
// declare module 'vue' {
//   export interface GlobalComponents {
//     //
//   }
// }
